# Generated by Django 4.1.2 on 2022-10-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "prioirty",
                    models.CharField(
                        choices=[
                            ("IMPORTANT", "Important Priority"),
                            ("HIGH", "High Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("LOW", "Low Priority"),
                        ],
                        max_length=120,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
