# Generated by Django 4.1.2 on 2022-10-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="prioirty",
            new_name="_prioirty",
        ),
    ]
