# Generated by Django 4.1.2 on 2022-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0002_rename_prioirty_task__prioirty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="_prioirty",
            field=models.CharField(
                choices=[
                    ("important", "Important Priority"),
                    ("high", "High Priority"),
                    ("medium", "Medium Priority"),
                    ("low", "Low Priority"),
                ],
                max_length=120,
            ),
        ),
    ]
