# Generated by Django 4.1.2 on 2022-10-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0004_alter_task__prioirty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="_prioirty",
        ),
    ]
