# Generated by Django 4.1.2 on 2022-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0005_remove_task__prioirty"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="help",
            field=models.CharField(default="hepl", max_length=2),
            preserve_default=False,
        ),
    ]
