# Generated by Django 4.1.2 on 2022-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0006_task_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="_prioirty",
            field=models.CharField(default="high", max_length=120),
            preserve_default=False,
        ),
    ]
