# Generated by Django 4.1.2 on 2022-10-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0007_task__prioirty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="_prioirty",
        ),
        migrations.AddField(
            model_name="task",
            name="prioirty",
            field=models.CharField(
                choices=[
                    ("important", "Important Priority"),
                    ("high", "High Priority"),
                    ("medium", "Medium Priority"),
                    ("low", "Low Priority"),
                ],
                default="High Priority",
                max_length=120,
            ),
            preserve_default=False,
        ),
    ]
