# Generated by Django 4.1.2 on 2022-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0008_remove_task__prioirty_task_prioirty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="prioirty",
            field=models.CharField(
                choices=[
                    ("important", "Important Priority"),
                    ("high", "High Priority"),
                    ("medium", "Medium Priority"),
                    ("low", "Low Priority"),
                ],
                default="low",
                max_length=120,
            ),
        ),
    ]
