# Generated by Django 4.1.2 on 2022-10-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0009_alter_task_prioirty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="prioirty",
        ),
    ]
